# <span style="color:darkblue"> Lecture 12a: Analyzing Experiments </span>

<font size = "5">

# <span style="color:darkblue"> I. Import Libraries </span>

In [1]:
# The "pandas" library is used for processing datasets
# The "numpy" is for numeric observations and random numbers
# The "matplotlib.pyplot" library is for creating graphs

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# We will "alias" two sublibraries in "statsmodels"
# "statsmodels.formula.api" contains functions to estimate models
# "statsmodels.api" contains general-use statistical options

import statsmodels.api as sm
import statsmodels.formula.api as smf
from statsmodels.iolib.summary2 import summary_col

<font size = "5">

Import data

In [53]:
dataset = pd.read_stata("data_raw/malawiexperiment.dta")

In [18]:
display(dataset)

,hhid,refchild,envelope_number,de_date,de_start,de_end,survey_version,q5c_school_code,q6_ra_id,q12_day,...,ln50p_invest_std_reg,ln50p_invest_std_miss,ln1_invest_std_reg,ln1_invest_std_miss,ln_invest_std_reg,ln_invest_std_miss,wtp_engl_math,ln10p_wtp_engl_math,ln50p_wtp_engl_math,ln_wtp_engl_math
0,4169,1,2,06/08/2012,16:05:01,16:20:21,74.0,4169,19.0,30,...,-100.000000,1.0,-0.500948,0.0,-100.000000,1.0,-200.0,-0.509496,-0.504247,-0.510826
1,4275,1,10,08/08/2012,10:54:24,11:07:18,74.0,B001,8.0,18,...,-0.070700,0.0,0.658406,0.0,-0.070733,0.0,175.0,2.045208,1.921813,2.079442
2,4086,1,10,08/08/2012,08:56:05,09:09:55,74.0,B001,11.0,18,...,-0.829332,0.0,0.362077,0.0,-0.829403,0.0,200.0,0.250998,0.249737,0.251315
3,4294,2,8,10/08/2012,13:27:16,13:45:03,74.0,B001,36.0,15,...,-100.000000,1.0,-0.012934,0.0,-100.000000,1.0,0.0,0.000000,0.000000,0.000000
4,14112,1,11,01/08/2012,09:36:12,09:51:37,74.0,B001,9.0,14,...,-100.000000,1.0,-100.000000,1.0,-100.000000,1.0,200.0,0.509496,0.504247,0.510826
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5263,9620,2,1,10/08/2012,08:32:23,08:47:04,74.0,P002,10.0,12,...,-0.059132,0.0,0.664002,0.0,-0.059165,0.0,400.0,0.845397,0.837886,0.847298
5264,9628,1,2,07/08/2012,14:53:44,15:10:06,74.0,P002,60.0,14,...,-0.571806,0.0,0.447550,0.0,-0.571861,0.0,0.0,0.000000,0.000000,0.000000
5265,9630,1,2,07/08/2012,15:10:12,15:28:26,74.0,P002,20.0,16,...,-0.817149,0.0,0.365794,0.0,-0.817218,0.0,0.0,0.000000,0.000000,0.000000
5266,9616,1,1,10/08/2012,08:14:29,08:31:51,74.0,P002,63.0,12,...,0.741472,0.0,1.131077,0.0,0.741457,0.0,0.0,0.000000,0.000000,0.000000
5267,9621,2,1,10/08/2012,08:47:29,09:01:30,74.0,P002,10.0,12,...,-3.127740,0.0,0.042854,0.0,-3.128442,0.0,100.0,0.688184,0.669050,0.693147

# <span style="color:darkblue"> II. Context </span>

<font size = "5">

Today we will review a paper by Rebecca Dizon-Ross published <br>
in the American Economic Review (2019).

- In this study, researchers partnered with local schools in Malawi <br>
- This study evaluated the impacts of information about children’s <br>
 academic performance on parents’ subsequent investments in their <br>
  children’s education.


https://www.povertyactionlab.org/evaluation/effects-student-performance-information-parental-decision-making-malawi?lang=fr

https://www.nber.org/papers/w24610

<font size = "5">

Intervention

- Parents in Malawi with low literacy levels had trouble interpreting <br>
school report cards. Many parents were unaware that their children were <br>
struggling with school.
- The intervention altered the way that the schools engaged with <br>
 parents. It had an impact on reducing the information gaps.

<font size = "5">

Experimental Design

- Students were assigned randomly to treatment and control <br>
with 50% probability
- The random assignment was done at the household level

<font size = "5">

Findings


<img src="figures/treatmenteffects_dizonross.png" alt="drawing" width="650"/>

<font size = "5">

At baseline (before the intervention)

- The graph on the left shows parental beliefs at baseline
- Parents of low performing students thought that they were doing <br>
better than they were. Ideally it should  be along the 45-degree line
- Similar results for treated and control groups at baseline because <br>
of randomization

At endline (after the intervention)

- Treated parents had more accurate perceptions of their children's <br>
performance
- The treatment effects varied depending on the baseline test scores

# <span style="color:darkblue"> II. Basic Descriptive Analysis </span>

<font size = "5">

Total number of children

In [3]:
len(dataset)

5268

<font size = "5">

Total number of households

- 2 children per households

In [32]:
unique_ids = pd.unique(dataset["hhid"])
len(unique_ids)

2634

<font size = "5">

Calculate number of treated and control

In [33]:
table = pd.crosstab(index = dataset['treat'],columns = "count")
table

col_0      count
treat
Control     2654
Treatment   2614

# <span style="color:darkblue"> III. Testing Covariate Balance </span>

<font size = "5">

Subset treated and control observations

In [54]:
dataset_treated = dataset.query('treat == "Treatment"')
dataset_control = dataset.query('treat == "Control"')

<font size = "5">

Socio-economic information can be collected at baseline <br>
(before the experiment)

In [35]:
variables_scores      = ["ave"]
variables_respondent  = ["lit","primary_resp_fem","age_par1","farmer"]
variables_household   = ["tot_kids","one_par"]
variables_student     = ["std","age","female","attendance_sv"]

<font size = "5" >

Check that characteristics are similar between treated and control <br>
at baseline

In [8]:
# Compute mean and standard deviation for the treated group
display(dataset_treated[variables_respondent].describe().loc[['mean', 'std']])

# Compute mean and standard deviation for the control group
display(dataset_control[variables_respondent].describe().loc[['mean', 'std']])

           lit  primary_resp_fem   age_par1    farmer
mean  0.675613          0.758990  40.974080  0.460587
std   0.468235          0.427778  11.290328  0.498541

           lit  primary_resp_fem   age_par1    farmer
mean  0.667426          0.773926  40.645455  0.465544
std   0.471225          0.418366  10.638597  0.498907

<font size = "5">

<font size = "5" >

Conduct a formal test of whether the coefficients are similar

- We should expect the coefficient on the treatment variable <br>
to be non-significant

In [36]:
reg_model = smf.ols("lit ~ treat ", dataset)
results = reg_model.fit(cov_type= "HC1")

print(summary_col(results,
                  stars = True))

============================
                      lit
----------------------------
Intercept          0.6674***
                   (0.0092)
treat[T.Treatment] 0.0082
                   (0.0130)
R-squared          0.0001
R-squared Adj.     -0.0001
============================
Standard errors in
parentheses.
* p<.1, ** p<.05, ***p<.01

<font size = "5">

Try it yourself!

<font size = "3">

- Obtain summary statistics for the mean and standard deviation for <br>
the other sets of baseline variables

In [13]:
# variables_scores      = ["ave"]
# variables_respondent  = ["lit","primary_resp_fem","age_par1","farmer"]
# variables_household   = ["tot_kids","one_par"]
# variables_student     = ["std","age","female","attendance_sv"]


display(dataset_treated[variables_scores].describe().loc[['mean', 'std']])
display(dataset_control[variables_scores].describe().loc[['mean', 'std']])

display(dataset_treated[variables_household].describe().loc[['mean', 'std']])
display(dataset_control[variables_household].describe().loc[['mean', 'std']])

display(dataset_treated[variables_student].describe().loc[['mean', 'std']])
display(dataset_control[variables_student].describe().loc[['mean', 'std']])

            ave
mean  46.357307
std   17.530622

            ave
mean  47.130746
std   17.448731

      tot_kids   one_par
mean  5.101760  0.198929
std   1.708462  0.399271

      tot_kids   one_par
mean  5.163527  0.186888
std   1.764395  0.389895

           std        age    female  attendance_sv
mean  3.723030  11.568383  0.499208       0.913829
std   1.370438   2.663856  0.500098       0.128672

           std        age    female  attendance_sv
mean  3.718161  11.664694  0.516784       0.915482
std   1.360581   2.686088  0.499816       0.129110

<font size = "5">

Try it yourself!

<font size = "3">

- Write a loop that runs different regressions of baseline covariates <br>
on the treatment variable. This can help you automate the process of <br>
testing for covariate balance

In [37]:
all_variables = variables_scores + variables_respondent + variables_household + variables_student

dataset_treated[all_variables].fillna(0, inplace=True)
dataset_control[all_variables].fillna(0, inplace=True)

In [39]:
# dataset_treated[all_variables] = dataset_treated[all_variables].apply(pd.to_numeric, errors='coerce')
# dataset_control[all_variables] = dataset_control[all_variables].apply(pd.to_numeric, errors='coerce')

In [55]:
display(dataset_treated[all_variables])

,ave,lit,primary_resp_fem,age_par1,farmer,tot_kids,one_par,std,age,female,attendance_sv
0,46,1.0,1,25.0,0.0,4,0,5,13.0,1.0,1.00
1,33,1.0,0,43.0,0.0,4,1,4,10.0,1.0,0.95
4,34,0.0,1,55.0,0.0,3,0,5,13.0,1.0,0.90
5,53,1.0,1,31.0,0.0,6,0,5,14.0,0.0,1.00
6,48,0.0,1,50.0,0.0,6,0,4,11.0,0.0,1.00
...,...,...,...,...,...,...,...,...,...,...,...
5258,70,1.0,0,32.0,0.0,4,0,5,12.0,0.0,1.00
5260,41,1.0,0,32.0,0.0,4,0,4,9.0,1.0,1.00
5261,46,1.0,0,35.0,0.0,5,0,6,13.0,1.0,1.00
5262,26,1.0,1,28.0,0.0,9,0,3,7.0,0.0,1.00
5264,78,1.0,1,28.0,0.0,9,0,4,9.0,0.0,1.00

In [42]:
dataset_control[all_variables].dtypes

ave                    int8
lit                 float64
primary_resp_fem       int8
age_par1            float64
farmer              float64
tot_kids               int8
one_par                int8
std                    int8
age                 float64
female              float64
attendance_sv       float32
dtype: object

In [51]:
dataset_treated.dropna(inplace=True)
dataset_control.dropna(inplace=True)

/var/folders/q1/01n67gwn27z65jnn2t76vm6w0000gn/T/ipykernel_73286/1363686105.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset_treated.dropna(inplace=True)
/var/folders/q1/01n67gwn27z65jnn2t76vm6w0000gn/T/ipykernel_73286/1363686105.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset_control.dropna(inplace=True)

In [56]:
print("lit~"+'tesrt')

lit~tesrt

In [61]:
# Write your own code

results = {}

for var in all_variables:
    # Regression for the treated group
    # X_treated = dataset_treated[[var]]
    # X_treated = sm.add_constant(X_treated)
    # y_treated = dataset_treated["treat"]
    treated_model = smf.ols("lit ~ "+var, dataset_treated)
    treated_results = treated_model.fit(cov_type = "HC1")
    results[var] = {"treated_summary": treated_results.summary()}

    control_model = smf.ols("lit ~ "+var, dataset_control)
    control_results = control_model.fit(cov_type = "HC1")
    results[var] = {"control_summary": control_results.summary()}

import pprint

pprint.pprint(results)

{'age': {'control_summary': <class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    lit   R-squared:                       0.018
Model:                            OLS   Adj. R-squared:                  0.017
Method:                 Least Squares   F-statistic:                     44.74
Date:                Thu, 10 Oct 2024   Prob (F-statistic):           2.76e-11
Time:                        11:00:27   Log-Likelihood:                -1650.7
No. Observations:                2519   AIC:                             3305.
Df Residuals:                    2517   BIC:                             3317.
Df Model:                           1
Covariance Type:                  HC1
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.9425      0.041     23.032      0.000       0.862       1.023
age           -0.0234      0.003     -6.689      0.000      -0.030      -0.017
==============================================================================
Omnibus:                    22738.239   Durbin-Watson:                   1.888
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              420.703
Skew:                          -0.705   Prob(JB):                     4.42e-92
Kurtosis:                       1.578   Cond. No.                         53.7
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
"""},
 'age_par1': {'control_summary': <class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    lit   R-squared:                       0.015
Model:                            OLS   Adj. R-squared:                  0.014
Method:                 Least Squares   F-statistic:                     31.95
Date:                Thu, 10 Oct 2024   Prob (F-statistic):           1.77e-08
Time:                        11:00:27   Log-Likelihood:                -1502.5
No. Observations:                2410   AIC:                             3009.
Df Residuals:                    2408   BIC:                             3021.
Df Model:                           1
Covariance Type:                  HC1
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.9191      0.038     24.356      0.000       0.845       0.993
age_par1      -0.0052      0.001     -5.653      0.000      -0.007      -0.003
==============================================================================
Omnibus:                     1310.002   Durbin-Watson:                   1.912
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              450.027
Skew:                          -0.899   Prob(JB):                     1.90e-98
Kurtosis:                       1.882   Cond. No.                         166.
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
"""},
 'attendance_sv': {'control_summary': <class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    lit   R-squared:                       0.006
Model:                            OLS   Adj. R-squared:                  0.006
Method:                 Least Squares   F-statistic:                     15.42
Date:                Thu, 10 Oct 2024   Prob (F-statistic):           8.84e-05
Time:                        11:00:27   Log-Likelihood:                -1737.2
No. Observations:                2614   AIC:                             3478.
Df Residuals:                    2612   BIC:                             3490.
Df Model:                           1
Covariance Type:                  HC1
=================================================================================
                    coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept         0.4039      0.068      5.968      0.000       0.271       0.536
attendance_sv     0.2860      0.073      3.926      0.000       0.143       0.429
==============================================================================
Omnibus:                    17766.631   Durbin-Watson:                   1.874
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              452.356
Skew:                          -0.698   Prob(JB):                     5.92e-99
Kurtosis:                       1.515   Cond. No.                         14.3
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
"""},
 'ave': {'control_summary': <class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    lit   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                 -0.000
Method:                 Least Squares   F-statistic:                    0.2248
Date:                Thu, 10 Oct 2024   Prob (F-statistic):              0.635
Time:                        11:00:26   Log-Likelihood:                -1755.0
No. Observations:                2634   AIC:                             3514.
Df Residuals:                    2632   BIC:                             3526.
Df Model:                           1
Covariance Type:                  HC1
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.6558      0.026     24.939      0.000       0.604       0.707
ave            0.0002      0.001      0.474      0.635      -0.001       0.001
==============================================================================
Omnibus:                    17351.709   Durbin-Watson:                   1.877
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              466.865
Skew:                          -0.711   Prob(JB):                    4.18e-102
Kurtosis:                       1.505   Cond. No.                         144.
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
"""},
 'farmer': {'control_summary': <class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    lit   R-squared:                       0.002
Model:                            OLS   Adj. R-squared:                  0.002
Method:                 Least Squares   F-statistic:                     5.714
Date:                Thu, 10 Oct 2024   Prob (F-statistic):             0.0169
Time:                        11:00:27   Log-Likelihood:                -1732.1
No. Observations:                2600   AIC:                             3468.
Df Residuals:                    2598   BIC:                             3480.
Df Model:                           1
Covariance Type:                  HC1
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.6868      0.012     55.225      0.000       0.662       0.711
farmer        -0.0444      0.019     -2.390      0.017      -0.081      -0.008
==============================================================================
Omnibus:                    17030.642   Durbin-Watson:                   1.888
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              456.458
Skew:                          -0.702   Prob(JB):                    7.61e-100
Kurtosis:                       1.503   Cond. No.                         2.54
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
"""},
 'female': {'control_summary': <class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    lit   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                 -0.000
Method:                 Least Squares   F-statistic:                    0.6514
Date:                Thu, 10 Oct 2024   Prob (F-statistic):              0.420
Time:                        11:00:27   Log-Likelihood:                -1694.1
No. Observations:                2546   AIC:                             3392.
Df Residuals:                    2544   BIC:                             3404.
Df Model:                           1
Covariance Type:                  HC1
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.6607      0.014     48.901      0.000       0.634       0.687
female         0.0151      0.019      0.807      0.420      -0.022       0.052
==============================================================================
Omnibus:                    17227.669   Durbin-Watson:                   1.889
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              451.786
Skew:                          -0.716   Prob(JB):                     7.87e-99
Kurtosis:                       1.513   Cond. No.                         2.66
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
"""},
 'lit': {'control_summary': <class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    lit   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 9.136e+31
Date:                Thu, 10 Oct 2024   Prob (F-statistic):               0.00
Time:                        11:00:26   Log-Likelihood:                 85287.
No. Observations:                2634   AIC:                        -1.706e+05
Df Residuals:                    2632   BIC:                        -1.706e+05
Df Model:                           1
Covariance Type:                  HC1
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   2.894e-15   9.78e-17     29.586      0.000     2.7e-15    3.09e-15
lit            1.0000   1.05e-16   9.56e+15      0.000       1.000       1.000
==============================================================================
Omnibus:                    17339.018   Durbin-Watson:                   0.170
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              467.005
Skew:                          -0.711   Prob(JB):                    3.90e-102
Kurtosis:                       1.505   Cond. No.                         3.23
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
"""},
 'one_par': {'control_summary': <class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    lit   R-squared:                       0.003
Model:                            OLS   Adj. R-squared:                  0.002
Method:                 Least Squares   F-statistic:                     6.375
Date:                Thu, 10 Oct 2024   Prob (F-statistic):             0.0116
Time:                        11:00:27   Log-Likelihood:                -1751.8
No. Observations:                2634   AIC:                             3508.
Df Residuals:                    2632   BIC:                             3519.
Df Model:                           1
Covariance Type:                  HC1
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.6788      0.010     67.256      0.000       0.659       0.699
one_par       -0.0609      0.024     -2.525      0.012      -0.108      -0.014
==============================================================================
Omnibus:                    17795.559   Durbin-Watson:                   1.881
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              462.808
Skew:                          -0.708   Prob(JB):                    3.18e-101
Kurtosis:                       1.514   Cond. No.                         2.67
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
"""},
 'primary_resp_fem': {'control_summary': <class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    lit   R-squared:                       0.024
Model:                            OLS   Adj. R-squared:                  0.024
Method:                 Least Squares   F-statistic:                     80.58
Date:                Thu, 10 Oct 2024   Prob (F-statistic):           5.18e-19
Time:                        11:00:26   Log-Likelihood:                -1722.8
No. Observations:                2634   AIC:                             3450.
Df Residuals:                    2632   BIC:                             3461.
Df Model:                           1
Covariance Type:                  HC1
====================================================================================
                       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept            0.8027      0.016     49.302      0.000       0.771       0.835
primary_resp_fem    -0.1750      0.019     -8.977      0.000      -0.213      -0.137
==============================================================================
Omnibus:                    20691.363   Durbin-Watson:                   1.868
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              428.915
Skew:                          -0.674   Prob(JB):                     7.28e-94
Kurtosis:                       1.553   Cond. No.                         3.98
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
"""},
 'std': {'control_summary': <class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    lit   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                 -0.000
Method:                 Least Squares   F-statistic:                    0.7046
Date:                Thu, 10 Oct 2024   Prob (F-statistic):              0.401
Time:                        11:00:27   Log-Likelihood:                -1754.8
No. Observations:                2634   AIC:                             3514.
Df Residuals:                    2632   BIC:                             3525.
Df Model:                           1
Covariance Type:                  HC1
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.6464      0.027     24.173      0.000       0.594       0.699
std            0.0056      0.007      0.839      0.401      -0.008       0.019
==============================================================================
Omnibus:                    17379.841   Durbin-Watson:                   1.878
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              466.566
Skew:                          -0.710   Prob(JB):                    4.86e-102
Kurtosis:                       1.506   Cond. No.                         12.2
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
"""},
 'tot_kids': {'control_summary': <class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    lit   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                 -0.000
Method:                 Least Squares   F-statistic:                    0.1327
Date:                Thu, 10 Oct 2024   Prob (F-statistic):              0.716
Time:                        11:00:27   Log-Likelihood:                -1755.0
No. Observations:                2634   AIC:                             3514.
Df Residuals:                    2632   BIC:                             3526.
Df Model:                           1
Covariance Type:                  HC1
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.6773      0.029     23.648      0.000       0.621       0.733
tot_kids      -0.0019      0.005     -0.364      0.716      -0.012       0.008
==============================================================================
Omnibus:                    17347.247   Durbin-Watson:                   1.877
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              466.921
Skew:                          -0.711   Prob(JB):                    4.07e-102
Kurtosis:                       1.505   Cond. No.                         17.4
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
"""}}

# <span style="color:darkblue"> IV. Calculating Average Treatment Effect </span>


- Make sure to use robust standard errors

<font size = "5">

Effect of treatment on endline beliefs

In [62]:
reg_model = smf.ols("u_ave ~ treat ", dataset)
results = reg_model.fit(cov_type= "HC1")

print(summary_col(results,
                  stars = True))

=============================
                     u_ave
-----------------------------
Intercept          63.5628***
                   (0.3435)
treat[T.Treatment] -7.4218***
                   (0.4988)
R-squared          0.0406
R-squared Adj.     0.0404
=============================
Standard errors in
parentheses.
* p<.1, ** p<.05, ***p<.01

<font size = "5">

Add baseline covariates

In [63]:
reg_model = smf.ols("u_ave ~ treat + ave ", dataset)
results = reg_model.fit(cov_type= "HC1")

print(summary_col(results,
                  stars = True))

=============================
                     u_ave
-----------------------------
Intercept          39.6549***
                   (0.6801)
treat[T.Treatment] -7.0564***
                   (0.4325)
ave                0.5079***
                   (0.0129)
R-squared          0.2725
R-squared Adj.     0.2722
=============================
Standard errors in
parentheses.
* p<.1, ** p<.05, ***p<.01

<font size = "5">

Test for heterogeneous effects

In [64]:
reg_model = smf.ols("u_ave ~ treat + ave + treat*ave", dataset)
results = reg_model.fit(cov_type= "HC1")

print(summary_col(results,
                  stars = True))

==================================
                          u_ave
----------------------------------
Intercept              49.1885***
                       (0.8840)
treat[T.Treatment]     -25.9979***
                       (1.2381)
ave                    0.3054***
                       (0.0177)
treat[T.Treatment]:ave 0.4055***
                       (0.0241)
R-squared              0.3095
R-squared Adj.         0.3091
==================================
Standard errors in parentheses.
* p<.1, ** p<.05, ***p<.01

<font size = "5">

Try it yourself!

Test for heterogeneous effects using other baseline covariates!

In [ ]:
# Write your own code